version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fintech-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fintech-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d fintech" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fintech-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fintech-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fintech-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - fintech-network

  # Placeholders for future services
  # spark-processor:
  #   build: ./services/spark-processor
  #   networks:
  #     - fintech-network

  # spring-api:
  #   build: ./services/spring-api
  #   networks:
  #     - fintech-network

  kafka-producer-python:
    build: ./services/kafka-producer-python
    container_name: fintech-producer-python
    depends_on:
      - kafka
    networks:
      - fintech-network

networks:
  fintech-network:
    driver: bridge
